codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "85...100"

  status:
    project:
      default:
        target: 85%
        threshold: 1%
        informational: false
        # This will fail the PR if coverage drops below 85%
    patch:
      default:
        target: 85%
        threshold: 1%
        informational: false
        # New code must have at least 85% coverage

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  unittests:
    paths:
      - src/
    carryforward: true

ignore:
  - "tests/**/*"
  - "config/**/*"
  - "docs/**/*"
  - "vendor/**/*"
